solidusio/circleci-orbs-extensions

- src/executors/postgres.yml
`DB=postgres` was not set so tests was running against the default database (`sqlite`)
> Fix postgres executor configuration

- src/executors/mysql-elasticsearch.yml
- src/executors/postgres-elasticsearch.yml
Now both mysql and postgres executors will have theirs elasticsearch
version.
> Add elasticsearch executors

- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
Now that we support Rails 6, extensions are built against a Rails 6 dummy app which uses Zeitwerk, which in turn requires Ruby >= 2.4.4.
> Update Ruby version to 2.4.7

- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
This is needed because Rails 6 requires Ruby 2.5, so in order for extensions to be testable with Rails 6 we need to provide them with the right Ruby version.
> Upgrade Ruby version to 2.5.6

- src/commands/test-branch.yml
Separates the `bundle install` and `bundle exec rake` commands in two steps, and saves the Bundler cache between the two. This way, even if `bundle exec rake` fails, the Bundler cache has already been saved and can be reused for subsequent test runs, which is especially useful to save time when iterating on a CircleCI failure.
> Save gems cache before running the tests

- src/commands/test-branch.yml
**WIP**: needs to be tested
At the moment if an extension specs run fails at one specific Solidus version (let's say 2.5), all the other steps are not performed. This makes hard to have a complete matrix in every scenario.
Using [`when: always`][1] ensure all the steps are executed, even if one of them fails.
[1]: https://circleci.com/docs/2.0/configuration-reference/#steps
Closes #7
> Avoid blocking other versions specs if one fails

- README.md
- src/commands/run-tests.yml
- src/commands/test-branch.yml
Ref: https://circleci.com/docs/2.0/configuration-reference/#store_test_results
Fixes #16 
This change allows CircleCI to nicely show the errors of the build in a nice summary view.
The typical way this will be used is to add the JUnit RSpec formatter and point its output toward the path set as environment variable:
```rb
RSpec::Core::RakeTask.new(:specs) do |t|
if ENV['TEST_RESULTS_PATH']
t.rspec_opts =
"--format progress " \
"--format RspecJunitFormatter --out #{ENV['TEST_RESULTS_PATH']}"
end
end
```
> Support CircleCI test results

- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
The `test_app` task uses the `DB` env var to build the dummy app using the correct database: MySQL or Postgres.
Set the ENV var to the correct Docker container to make it works.
> Allow the test_app to use the correct database

- .circleci/config.yml
V9 has breaking changes that break the current CI config.
> Prevent orb-tools to update to the latest major

- src/commands/run-tests-solidus-current.yml
- src/commands/run-tests-solidus-master.yml
- src/commands/run-tests-solidus-older.yml
- src/commands/run-tests.yml
- src/commands/store-test-results.yml
_this PR replaces #18_
Allow users to target a specific semantic group and allow them to mix
and match them independently. Every group will target a single version
except for the "older" group that will include all versions from the
last third (included) down to the oldest supported version.
Using a configuration like this:
```yml
jobs:
- solidusio_extensions/run-specs-master
- solidusio_extensions/run-specs-current
- solidusio_extensions/run-specs-previous
- solidusio_extensions/run-specs-older
```
Brought the CI time from 20m down to less than 3m.
The default way of running specs across multiple Solidus versions is to do that sequentially within a single job. By doing that in parallel instead of having to wait the sum total times for each Solidus version it will allow to wait just for …
> Use semantic Solidus versions

- src/commands/run-tests-solidus-older.yml
Fixes the execution order of tests for older versions of Solidus. Currently, it's running 2.9, then 2.8, then 2.7, which is a bit weird (although not a real bug).
> Fix test execution order for older versions of Solidus

- src/executors/sqlite-memory.yml
This will come useful for faster CI execution for specs that don't
really use the database. 
_Extracted from #19_
> Add an in-memory sqlite executor

- src/commands/run-tests-solidus-older.yml
2.7.0 was released at 09/14/2018 and according to the Version Guidelines
it's end of life is 03/14/2020.
This commits removes the branch from the testing support.
> Remove v2.7 branch since 2.7 is EOL

- src/commands/test-branch.yml
Ensure old gems are cleaned after a new bundle install and that we have a different gem cache for each solidus branch.
The reason is that recently I caught a repo that spent 5min restoring and then saving more than 5GB of cache. This change will ensure all unused gem and git versions are pruned and that old solidus version caches will be abandoned once the support for that version is dropped.
This change was tried here https://github.com/solidusio-contrib/solidus_importer/pull/32
Before:
https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_importer/263/workflows/1a2db93d-25f2-46f6-8f94-bb5226b776e8/jobs/555
After:
https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_importer/272/workflows/91ab5c28-51eb-4a6c-83e7-068eb1ef8ed1/jobs/571
> Bundle clean

- src/commands/test-branch.yml
Many tools are already configured to ignore the vendor/bundle path.
By moving to subfolders we avoid reconfiguring them while still
retaining the benefits of per-branch bundles.
The command also includes a couple of lines to support the migration from the old path, saving a ton of time for all extensions that will get this update. The migration code will be removed after Dec 1 2020, see https://github.com/solidusio/circleci-orbs-extensions/issues/30.
---
**Before:**
https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_paypal_commerce_platform/255/workflows/f2e785b8-c256-4771-9477-110cb03f165c/jobs/638
**After:**
https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_paypal_commerce_platform/259/workflows/b65034e9-e64f-498b-b1e2-f0babfdd3659/jobs/651
> Keep cached bundles into vendor/bundle

- src/commands/run-tests-solidus-older.yml
Removes Solidus 2.8 from the build matrix, since it [reached EOL](https://solidus.io/security/) on 2020-07-29.
> Remove Solidus 2.8 from the build matrix

- src/commands/test-branch.yml
All extensions are expected to be up-to-date by now.
Fixes #30.
Partially reverts #29.
> Remove old bundle path migration code

- src/commands/test-branch.yml
- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
- src/executors/sqlite-memory.yml
Ruby 2.6 has reached EOL and will no longer receive any security
patches after March 31, 2022. Bumped version requirements to 2.7 as
it is best practiced to use a maintained version of Ruby.
> [semver:major] Ruby 2.5 and Ruby 2.6 has reached EOL, bump CI environment to 2.7 

- src/examples/extension.yml
- src/executors/postgres.yml
This pull request fixes two issues blocking Solidus extensions from running on CI:
1. Create the `postgres` role to fix: "PG::ConnectionBad: FATAL:  role "postgres" does not exist"
2. Call the CircleCI step required to install Google Chrome (https://circleci.com/developer/images/image/cimg/ruby#browsers)
Some examples of failing extensions:
- https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_social/188/workflows/b34f7de8-b3a5-45b0-ab29-dbf98c2352d4/jobs/422
- https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_shipstation/206/workflows/d428bc33-378f-4556-a403-99707b3ebfae/jobs/520
- https://app.circleci.com/pipelines/github/SuperGoodSoft/solidus_taxjar/473/workflows/5a621dbb-a3d5-44f0-8095-cf7cfc36ae92/jobs/650
> Fix container configuration

- src/commands/test-branch.yml
We discovered that solidus master was not being updated because a simple `install` was relying on the restored cache.
E.g. in https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_subscriptions/693/workflows/f5d183ae-4dd7-4cea-a502-7c4dee49624e/jobs/1875 we fetched solidus_core 3.2.0.alpha from https://github.com/solidusio/solidus.git at master@094bd7d instead of master@d467123b9.
> Run `bundle update solidus` every time

- README.md
- src/examples/extension.yml
- src/executors/sqlite.yml
Ref: https://github.com/solidusio/solidus/pull/4525#discussion_r953139737
> Add a sqlite executor (not in-memory)

- .circleci/test-deploy.yml
- Add solidus to the dummy gemfile
- Move the dummy extension creation to a command
- Run tests for all versions of solidus
- Mix executors with solidus versions to increase coverage keeping execution time low
> Improve the Orb testing coverage

- src/commands/test-branch.yml
When using system specs, Rails automatically generate screenshots for
failing tests using ScreenshotHelper but it has no options to set the
output path.
_Continuing from https://github.com/solidusio/circleci-orbs-extensions/pull/34_
cc @blocknotes
> Store Rails screenshots in artifacts

- src/commands/test-branch.yml
On #44, we added `bundle update solidus` to be sure bundle cache was
invalidated. However, that fails for extensions that don't have solidus
in their Gemfile (e.g., solidus_frontend).
We try another strategy by ignoring the previous lock file when
generating the new one. From `bundle lock --help`:
> Usage:
>   bundle lock
>
> Options:
>       [--update=ignore the existing lockfile, update all gems by default, or update list of given gems]
> Ignore old lock file instead of updating Solidus

- src/commands/test-branch.yml
Both --path and --clean are deprecated:
```
[DEPRECATED] The `--clean` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local clean 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle/v3.0'`, and stop using this flag
```
> Use local configurations instead of deprecated options for bundler

- src/examples/extension.yml
- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
- src/executors/sqlite-memory.yml
- src/executors/sqlite.yml
This will allow us to test against multiple versions of ruby and for newer versions of databases without requiring an update in the Orb.
Fixes #51
> Allow versions in executors to be parameterized

- src/commands/test-branch.yml
solidusio/solidus_frontend#15 fixed the generation of the dummy application used during the extensions testing. However, we still need to pass the SKIP_SOLIDUS_BOLT on Solidus v3.2, where that change hasn't been backported yet. We can revert this commit once that happens.
@elia, I haven't found a way to be more specific and pass the environment variable only to v3.2 (at least without a big restructure). Please, tell me if I'm missing something. Anyway, this is only a temporary fix until the commit in solidus_frontend is backported.
cc @cpfergus1
> Set SKIP_SOLIDUS_BOLT environment variable

- src/commands/test-branch.yml
_Take 2_
"master" is not a valid version, switching to `null` hoping that the environment variable will turn out as `nil` in Ruby.
Ref: https://github.com/solidusio/solidus_paypal_commerce_platform/pull/139
The following are not always needed (~cross them out~ if they are not):
> Fix the default rails version

- src/commands/run-tests-solidus-older.yml
We removed support for v3.1 on https://github.com/solidusio/circleci-orbs-extensions/pull/73. However, it'll reach [EOL on 2023-03-10](https://solidus.io/security/).
We'll cover older Rails with it, while using Rails v7 for Solidus v3.2.
- ~[ ] I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).~
The following are not always needed (~cross them out~ if they are not):
- ~[ ] I have added automated tests to cover my changes.~
- ~[ ] I have attached screenshots to demo visual changes.~
- ~[ ] I have opened a PR to update the …
> Add supported v3.1, and use older Rails on it

- src/commands/test-branch.yml
We're using dynamic test results paths because for extensions using an
older setup different solidus versions are tested within the same job.
However, we don't need to mimic the entire cache key as path. CircleCI
doesn't interpolate everything within environment variable values, so
breaking this coupling will help in the future.
Closes #78
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the …
> Simplify the default test results path

- src/commands/test-branch.yml
We started allowing to use different ruby version but was never included in the cache key.
The following are not always needed (~cross them out~ if they are not):
> Track the ruby version in the cache key

- src/commands/test-branch.yml
Allow extensions to invalidate bundle cache
Until now, there were no way for an extension to invalidate its bundle cache. Instead, it was needed to bump the cache version upstream in the orb's code. That also meant that all of the extensions cache was invalidated at once.
We're now giving control to individual extensions by adding a `CACHE_VERSION` [environment variable to the cache keys](https://support.circleci.com/hc/en-us/articles/115015426888-Clear-Project-Dependency-Cache). When no present in the extension's environment, it'll take a value equal to `<no value>`, and it can be added and bumped to invalidate it.
Closes #77
The following are …
> Allow individual extensions to clear bundler cache

- src/commands/run-tests-solidus-older.yml
That version is [EOL since 2023-03-10](https://solidus.io/security/).
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Remove v3.1 from older Solidus

- src/examples/extension.yml
Ruby 2.7 reached EOL on 2023-03-31, while 3.2 was released on 2022-12-25. See https://www.ruby-lang.org/en/downloads/branches/.
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Update rubies in the example configuration

- .circleci/test-deploy.yml
- solidus_dummy_extension/.rubocop.yml
Ruby 2.7 is no longer supported on Solidus' master.
The following are not always needed:
- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.
> Fix CI by explicitly passing ruby version

- src/examples/extension.yml
- src/executors/mysql-elasticsearch.yml
- src/executors/mysql.yml
- src/executors/postgres-elasticsearch.yml
- src/executors/postgres.yml
- src/executors/sqlite-memory.yml
- src/executors/sqlite.yml
Ruby 2.7 has been end-of-lifed: https://endoflife.date/ruby.
Not updating to 3.0 can cause dependency installation issues. For example: extensions that use `selenium-webdrivers`, `~> 4.11`, require Ruby 3 at a minimum.
> Update from Ruby 2.7 to 3.0

- src/commands/test-branch.yml
This fixes the cleanup task of the test-branch file that is run in every test. For extensions that use Solidus core's `DummyApp` rather than the dummy app generated by the solidus_dev_support extension, there are no executables. Cleanup happens via a Raketask supplied by Solidus itself.
Fixes spec failures such as this one https://app.circleci.com/pipelines/github/friendlycart/solidus_friendly_promotions/471/workflows/14e177b0-508e-4ed1-8943-e0163720785a/jobs/1548
when using the Solidus core dummy app in extensions like here https://github.com/friendlycart/solidus_friendly_promotions/pull/124.
> Allow single-file Dummy App in extensions

- solidus_dummy_extension/Gemfile
SQLite has 2.0 out, but ActiveRecord still relies on 1.x in their generators.
> Restrict SQLite to 1.x

- src/commands/test-branch.yml
Some extensions have rake defined, but no dummy app and therefore no database (i.e. solidus_dev_support). In these cases we don't need to run `rake db:drop`.
> Drop database only if dummy app present

- src/commands/run-tests-solidus-older.yml
Solidus 4.0 through 4.2 are not compatible with Rails 7.2, but the version requirement `~> 7.0`  allows Rails 7.2.
> Fix requirements for older solidus versions

- src/commands/run-tests-solidus-older.yml
Solidus 4.0 is not supported anymore. EOL was 2024-11-08
> Remove Solidus 4.0 builds

- src/commands/test-branch.yml
This is the minimum version we support.
In order to prevent installing Rails 8.0
during extension specs we need to default
to the 7.x version.
> Set default Rails version to v7.0
